# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt

# Migrate to build.os
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
